//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConanExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConanExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///      {
        ///        &quot;Data&quot;: &quot;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=&quot;,
        ///        &quot;Index&quot;: &quot;16513&quot;,
        ///        &quot;Symbol&quot;: &quot;　&quot;
        ///      },
        ///      {
        ///        &quot;Data&quot;: &quot;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAYAAwABAA=&quot;,
        ///        &quot;Index&quot;: &quot;16769&quot;,
        ///        &quot;Symbol&quot;: &quot;、&quot;
        ///      },
        ///      {
        ///        &quot;Data&quot;: &quot;AAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAIgAiACIAHAA=&quot;,
        ///        &quot;Index&quot;: &quot;17025&quot;,
        ///        &quot;Symbol&quot;: &quot;。&quot;
        ///      },
        ///      {
        ///        &quot;Data&quot;: &quot;AAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAcAAwABAAIAA=&quot;,
        ///        &quot;Index&quot;: &quot;17281&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultLockedCharacters {
            get {
                return ResourceManager.GetString("DefaultLockedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font1 {
            get {
                object obj = ResourceManager.GetObject("font1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset;OriginalLength;OriginalString;Translation;Translation_EN;Position im Spiel;Zusammenhang
        ///3204;10;はじめから;neu       ;New Game;Hauptmenü;
        ///3216;10;つづきから;fortsetzen;Continue;Hauptmenü;
        ///3228;18;最初から始めます。;Ein neues Spiel   ;Start a           ;Hauptmenü;
        ///3248;16;よろしいですか？;starten?        ;new game?       ;Hauptmenü;
        ///3552;32;メモリーカードのチェック中です。;Memory Card wird gelesen.       ;Reading Memory Card.            ;Hauptmenü;
        ///3600;30;クリアデータ専用ファイルを更新;Möchtest du deine Ergebnisse  ;Do you want to update your;Memory C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SLPS_016 {
            get {
                return ResourceManager.GetString("SLPS_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WINDOW {
            get {
                object obj = ResourceManager.GetObject("WINDOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MordunterMitschülernWelcheStorysollesseinMordunterMitschülernMordunterMitschülernDerSchatzaufeinereinsamenInselMordunterMitschülernEinneuesSpielwirdbegonnenBistdueinverstandenJaNeinGutesGelingenDuYumichanwirwerdendochfürimmerFreundeseinKlarVersprochenVersprochenMordunterMitschülernRanistesnochweitÄchzMenschduhastechtkeinDurchhaltevermögenDaskommtdavondassduimmersovieltrinkstJetztreißdichzusammenDuauchRankundubistdochschließlicheinJungeVergleichnichtdieAusdauereinesKapitänsdesKarateKlubsmitdereinesGrundschül [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordlist_long {
            get {
                return ResourceManager.GetString("wordlist_long", resourceCulture);
            }
        }
    }
}
